### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by geekzxiang** [huannan/XArch#3]
* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by geekzxiang** [comment]
`Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
	at androidx.room.verifier.DatabaseVerifier.<clinit>(DatabaseVerifier.kt:71)
	... 50 more`

不知道是不是哪里跟M1的mac不兼容

**Comment by huannan** [comment]
是最新版本的AS吗？

**Comment by geekzxiang** [comment]
![image](https://user-images.githubusercontent.com/5501481/133710766-1c757a74-982d-4362-b5e4-b37f615cb19a.png)
是的，这个版本

**Comment by huannan** [comment]
百度了一下，这个确实是M1的兼容性问题，这个我也不知道怎么解决了。或者试试降级gradle

**Comment by geekzxiang** [comment]
https://blog.csdn.net/qq_36800514/article/details/115081914
看了下，的确有不兼容问题
