### ISSUE TITLE
XArchApplication初始化

### ISSUE THREAD

**Issue by geekzxiang** [huannan/XArch#5]
请教一下，主进程的初始化，为什么要遍历进程，匹配到当前进程才初始化？按道理onCreate的执行不就是当前进程么？

**Comment by huannan** [comment]
要考虑多进程的问题，每个进程只初始化需要的SDK，这样可以提高启动效率，另外有一些SDK需要多进程使用的话，就不匹配进程。

当然，目前这个项目没有这种问题，主要是公司的项目遇到的问题，所以就提交到开源项目里面mark一下而已
